apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-app
spec:
  containers:
    - name: nginx
      image: nginx:1.16.1
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "200Mi"